
spring:
  application:
    name: canary
  profiles:
    active: local

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

mybatis-plus:
  global-config:
    banner: on
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0


