
spring:
  application:
    name: canary
  profiles:
    active: local
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true

mybatis-plus:
  global-config:
    banner: on
    db-config:
      logic-delete-field: deleted

token:
  secret: canary
  expires: 7200s


