
spring:
  application:
    name: canary
  profiles:
    active: local

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true

mybatis-plus:
  global-config:
    banner: on
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: deleted


