spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:16033/canary?characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: proxy.admin
    password: Pass!234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 20
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      pool-name: CanaryHikariPool
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      # 连接超时时长（毫秒）
      timeout: 6000ms
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 5
  servlet:
    multipart:
      location: /Users/zhaohongliang/Desktop

logging:
  config: classpath:logback-spring.xml
  file:
    path: /Users/zhaohongliang/Desktop/log
  level:
    com.example.canary: debug

task:
  # 是否开启 scheduled
  auto-execute: false
  monitor:
    # 是否开启监测任务
    enabled: false
    # 监测任务执行频率
    cron: 0/5 * * * * ?

token:
  secret: canary
  timeout: 7200s
