
spring:
  application:
    name: canary
  profiles:
    active: local
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

mybatis-plus:
  global-config:
    banner: off
    db-config:
      logic-delete-field: deleted
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-spring.xml

token:
  secret: canary
  timeout: 7200s


