
spring:
  application:
    name: canary
  profiles:
    active: '@profileActive@'
  pid:
    file: ./canary.pid
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 0

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

mybatis-plus:
  global-config:
    banner: off
    db-config:
      id-type: assign_uuid
      logic-delete-field: deleted
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        # 开启 shutdown 端点访问
        include: shutdown
  endpoint:
    shutdown:
      # 开启 shutdown 实现优雅停服
      enabled: true


